### ISSUE TITLE
Searching for MP3 File Loop

### ISSUE THREAD

**Issue by oakgem217** [Alee14/DLMP3#1]
I've installed the bot correctly (afaik), and have the config set up as well. The issue I'm running into is that the bot can't seem to find the mp3 files I put in it's music folder. I have some files in there, but when I run the bot, I get back the message "
Searching .mp3 file...
Music has finished playing.
Searching .mp3 file...
" etc. on repeat until I stop the bot.

**Comment by Alee14** [comment]
Solving it on the Discord server...
