### ISSUE TITLE
Cannot connect to voice channel

### ISSUE THREAD

**Issue by br8kpoint** [Alee14/DLMP3#2]
Hi,

I followed your video tutorial but when I run the bot it throws an exception

```
Error [VOICE_JOIN_CHANNEL]: You do not have permission to join this voice channel.
(node:55677) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
```

I have set the ouath permissions to &permissions=49283840&scope=bot

which lets the bot connect to the voice channel, speak, video,mute members, deafen members,use voice activity,priority speaker.

![Screen Shot 2021-04-22 at 11 58 28 PM](https://user-images.githubusercontent.com/1423119/115816348-b75b5400-a3c6-11eb-8f7e-dda5abc4cdb9.png)

Is there something I am missing?

**Comment by Alee14** [comment]
Have you tried changing the channel's permission?
